# Site settings
title: plainlanguage.gov
description: Plain language makes it easier for the public to read, understand, and use government communications.
email: info@plainlanguage.gov
image: /assets/img/twitter_profile.png
facebook: https://www.facebook.com/plainlanguagegov-174397429237337/
twitter: https://twitter.com/govplainlang/
pinterest: https://pinterest.com/plact2010/
linkedin: https://www.linkedin.com/showcase/plain-language-action-and-information-network-plain-/
instagram: https://www.instagram.com/govplainlang/
github:
  organization: GSA
  repository: plainlanguage.gov
  default_branch: main

sitewide_notification:
  display: true
  heading: Information Status
  text: >-
    We are currently revising content on plainlanguage.gov, including the federal guidelines, training materials, and other online resources. Weâ€™ve temporarily paused accepting training requests until after this update is complete. We hope to resume training later in the fall 2023.


theme: uswds-jekyll
url: "https://plainlanguage.gov" # the base hostname & protocol for your site
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - CONTRIBUTING.md
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - vendor
  - webpack.config.js

keep_files:
  - /assets/js/build/bundle.js

scripts:
  - /assets/js/build/bundle.js
  - /assets/uswds/js/uswds.min.js

styles:
  - href: /assets/css/main.css
    media: screen, print

sass:
  load_paths:
    - _sass
    - node_modules
  style: compressed

defaults:
  - scope:
      path: "assets/uswds"
    values:
      skip_index: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "docs"
  - scope:
      path: "_pages/guidelines"
    values:
      pagination: true

collections:
  pages:
    output: true
    permalink: /:path/

kramdown:
  parse_block_html: true

jekyll_pages_api_search:
  skip_index: false
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
  results_page_title: Search results
