# Site settings
title: plainlanguage.gov
description: Resources to help federal employees deliver clear communications to the public.
email: plainlanguage@gsa.gov

# Using https://github.com/18F/uswds-jekyll
theme: uswds-jekyll

# GA and GitHub data
# google_analytics_ua: UA-99995535-1
repo: https://github.com/GSA/plainlanguage.gov

plugins:
  - jekyll-redirect-from

exclude:
  - CONTRIBUTING.md
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - vendor

styles:
  - /assets/css/main.css

sass:
    load_paths:
        - _sass
        - node_modules

defaults:
  - scope:
      path: "assets/uswds"
    values:
      skip_index: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "docs"

collections:
  pages:
    output: true
    permalink: /:path/

kramdown:
  parse_block_html: true

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
